services:
  db:
    image: postgres:15
    container_name: cine_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - cine_data:/var/lib/postgresql/data

volumes:
  cine_data:
